networks:
  app-tier:
    driver: bridge


services:
  app:
    build: .
    command: sh -c "alembic upgrade head &&
                    uvicorn app:app --reload --host=0.0.0.0 --port=8000"
    depends_on:
      - db
      - minio
    volumes:
      - ./app:/app/app
    ports:
      - '8000:8000'
    environment:
      DB_HOST: db
      MINIO_SERVER_ACCESS_KEY: ${ACCESS_KEY}
      MINIO_SERVER_SECRET_KEY: ${SECRET_KEY}
    networks:
      - app-tier
    env_file:
      - .env


  db:
      image: postgres
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
        POSTGRES_DB: ${DB_NAME}
      ports:
        - "5432:5432"
      volumes:
        - .postgres:/var/lib/postgres/data
      restart: always
      networks:
        - app-tier
      env_file:
        - .env

  minio:
    depends_on:
      - db
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioroot
      MINIO_ROOT_PASSWORD: miniopassword
    networks:
      - app-tier
    env_file:
      - .env